### ISSUE TITLE
tspart_cli segmentation fault Savers.cc

### ISSUE THREAD

**Issue by ronansalmon** [quinor/tspart#1] opened 2021-05-21 07:09 UTC
Hi,

I've tried tspart_gui, no problem, great tool !
I wanted to try out tspart_cli, but it crashes all the time : segmentation fault.
```
./tspart_cli 2014.jpg
[    0.184 ] [ Info     ] [ Entering ] Block Input (1)
[    0.184 ] [ Info     ] [ Exiting  ]     Block Input (1)
[    0.184 ] [ Info     ] [ Entering ] Block ImageLoader (2)
[    0.184 ] [ Verbose  ]                  Filename: 2014.jpg
[    0.383 ] [ Info     ] [ Exiting  ]     Block ImageLoader (2)
[    0.383 ] [ Info     ] [ Entering ] Block Input (8)
[    0.383 ] [ Info     ] [ Exiting  ]     Block Input (8)
[    0.383 ] [ Info     ] [ Entering ] Block ImageMaximizer (9)
[    0.383 ] [ Verbose  ]                  Size before maximizing: (1144, 600)
[    0.384 ] [ Verbose  ]                  Size after maximizing: (2048, 1074.13)
[    0.403 ] [ Info     ] [ Exiting  ]     Block ImageMaximizer (9)
[    0.403 ] [ Info     ] [ Entering ] Block ImageFilterGrayscale (11)
[    0.421 ] [ Info     ] [ Exiting  ]     Block ImageFilterGrayscale (11)
[    0.422 ] [ Info     ] [ Entering ] Block Input (15)
[    0.422 ] [ Info     ] [ Exiting  ]     Block Input (15)
[    0.422 ] [ Info     ] [ Entering ] Block ImageFilterGaussianBlur (16)
[    0.422 ] [ Verbose  ]                  Gaussian blur sigma: 1
[    0.465 ] [ Info     ] [ Exiting  ]     Block ImageFilterGaussianBlur (16)
[    0.465 ] [ Info     ] [ Entering ] Block Input (5)
[    0.465 ] [ Info     ] [ Exiting  ]     Block Input (5)
[    0.465 ] [ Info     ] [ Entering ] Block ImageFilterGaussianBlur (12)
[    0.465 ] [ Verbose  ]                  Gaussian blur sigma: 20
[    0.471 ] [ Info     ] [ Exiting  ]     Block ImageFilterGaussianBlur (12)
[    0.471 ] [ Info     ] [ Entering ] Block ImageFilterGrayscale (14)
[    0.516 ] [ Info     ] [ Exiting  ]     Block ImageFilterGrayscale (14)
[    0.517 ] [ Info     ] [ Entering ] Block ImageCompositorRatio (18)
[    0.547 ] [ Info     ] [ Exiting  ]     Block ImageCompositorRatio (18)
[    0.547 ] [ Info     ] [ Entering ] Block Input (7)
[    0.548 ] [ Info     ] [ Exiting  ]     Block Input (7)
[    0.548 ] [ Info     ] [ Entering ] Block Input (6)
[    0.548 ] [ Info     ] [ Exiting  ]     Block Input (6)
[    0.548 ] [ Info     ] [ Entering ] Block ImageFilterSigmoid (19)
[    0.548 ] [ Verbose  ]                  Sigmoid function: atan((x + 25) * 2.25)
[    0.558 ] [ Info     ] [ Exiting  ]     Block ImageFilterSigmoid (19)
[    0.558 ] [ Info     ] [ Entering ] Block Input (4)
[    0.558 ] [ Info     ] [ Exiting  ]     Block Input (4)
[    0.558 ] [ Info     ] [ Entering ] Block ImageFilterLogarithm (22)
[    0.558 ] [ Verbose  ]                  Log brightness correction: log(1+x/256*8)/log(1+8)
[    0.563 ] [ Info     ] [ Exiting  ]     Block ImageFilterLogarithm (22)
[    0.564 ] [ Info     ] [ Entering ] Block ImageFilterInverse (25)
[    0.577 ] [ Info     ] [ Exiting  ]     Block ImageFilterInverse (25)
[    0.578 ] [ Info     ] [ Entering ] Block Input (24)
[    0.578 ] [ Info     ] [ Exiting  ]     Block Input (24)
[    0.578 ] [ Info     ] [ Entering ] Block GrayscaleImageToScalarField (26)
[    0.578 ] [ Verbose  ]                  Conversion scale is 2
[    1.800 ] [ Verbose  ]                  Upscale: [    0 / 2148 ]
[    1.819 ] [ Verbose  ]                  Upscale: [  214 / 2148 ]
[    1.840 ] [ Verbose  ]                  Upscale: [  428 / 2148 ]
[    1.855 ] [ Verbose  ]                  Upscale: [  642 / 2148 ]
[    1.869 ] [ Verbose  ]                  Upscale: [  856 / 2148 ]
[    1.884 ] [ Verbose  ]                  Upscale: [ 1070 / 2148 ]
[    1.902 ] [ Verbose  ]                  Upscale: [ 1284 / 2148 ]
[    1.918 ] [ Verbose  ]                  Upscale: [ 1498 / 2148 ]
[    1.934 ] [ Verbose  ]                  Upscale: [ 1712 / 2148 ]
[    1.958 ] [ Verbose  ]                  Upscale: [ 1926 / 2148 ]
[    1.996 ] [ Verbose  ]                  Upscale: [ 2140 / 2148 ]
[    1.996 ] [ Info     ] [ Exiting  ]     Block GrayscaleImageToScalarField (26)
[    1.997 ] [ Info     ] [ Entering ] Block ScalarFieldMassPrefixSum (28)
[    2.135 ] [ Info     ] [ Exiting  ]     Block ScalarFieldMassPrefixSum (28)
[    2.135 ] [ Info     ] [ Entering ] Block Input (29)
[    2.136 ] [ Info     ] [ Exiting  ]     Block Input (29)
[    2.136 ] [ Info     ] [ Entering ] Block PointsGenerator (30)
[    2.136 ] [ Verbose  ]                  Fill is 27
[    2.136 ] [ Verbose  ]                  Progress through Hilbert curve: [        0 / 16777216 ]
[    2.167 ] [ Verbose  ]                  Progress through Hilbert curve: [  1048576 / 16777216 ]
[    2.192 ] [ Verbose  ]                  Progress through Hilbert curve: [  2097152 / 16777216 ]
[    2.223 ] [ Verbose  ]                  Progress through Hilbert curve: [  3145728 / 16777216 ]
[    2.248 ] [ Verbose  ]                  Progress through Hilbert curve: [  4194304 / 16777216 ]
[    2.275 ] [ Verbose  ]                  Progress through Hilbert curve: [  5242880 / 16777216 ]
[    2.302 ] [ Verbose  ]                  Progress through Hilbert curve: [  6291456 / 16777216 ]
[    2.356 ] [ Verbose  ]                  Progress through Hilbert curve: [  7340032 / 16777216 ]
[    2.391 ] [ Verbose  ]                  Progress through Hilbert curve: [  8388608 / 16777216 ]
[    2.426 ] [ Verbose  ]                  Progress through Hilbert curve: [  9437184 / 16777216 ]
[    2.458 ] [ Verbose  ]                  Progress through Hilbert curve: [ 10485760 / 16777216 ]
[    2.489 ] [ Verbose  ]                  Progress through Hilbert curve: [ 11534336 / 16777216 ]
[    2.517 ] [ Verbose  ]                  Progress through Hilbert curve: [ 12582912 / 16777216 ]
[    2.545 ] [ Verbose  ]                  Progress through Hilbert curve: [ 13631488 / 16777216 ]
[    2.579 ] [ Verbose  ]                  Progress through Hilbert curve: [ 14680064 / 16777216 ]
[    2.611 ] [ Verbose  ]                  Progress through Hilbert curve: [ 15728640 / 16777216 ]
[    2.638 ] [ Info     ] [ Exiting  ]     Block PointsGenerator (30)
[    2.638 ] [ Info     ] [ Entering ] Block PointsVoronoiDelaunay (32)
[    2.638 ] [ Info     ] [ Exiting  ]     Block PointsVoronoiDelaunay (32)
[    2.638 ] [ Info     ] [ Entering ] Block PointsRelaxator (33)
[    2.639 ] [ Info     ] [ Exiting  ]     Block PointsRelaxator (33)
[    2.639 ] [ Info     ] [ Entering ] Block PointsVoronoiDelaunay (34)
[    2.639 ] [ Info     ] [ Exiting  ]     Block PointsVoronoiDelaunay (34)
[    2.639 ] [ Info     ] [ Entering ] Block PointsRelaxator (35)
[    2.639 ] [ Info     ] [ Exiting  ]     Block PointsRelaxator (35)
[    2.639 ] [ Info     ] [ Entering ] Block PointsVoronoiDelaunay (36)
[    2.639 ] [ Info     ] [ Exiting  ]     Block PointsVoronoiDelaunay (36)
[    2.639 ] [ Info     ] [ Entering ] Block PointsRelaxator (37)
[    2.639 ] [ Info     ] [ Exiting  ]     Block PointsRelaxator (37)
[    2.639 ] [ Info     ] [ Entering ] Block PointsVoronoiDelaunay (38)
[    2.639 ] [ Info     ] [ Exiting  ]     Block PointsVoronoiDelaunay (38)
[    2.639 ] [ Info     ] [ Entering ] Block PointsRelaxator (39)
[    2.639 ] [ Info     ] [ Exiting  ]     Block PointsRelaxator (39)
[    2.639 ] [ Info     ] [ Entering ] Block PointsVoronoiDelaunay (40)
[    2.639 ] [ Info     ] [ Exiting  ]     Block PointsVoronoiDelaunay (40)
[    2.639 ] [ Info     ] [ Entering ] Block PointsRelaxator (41)
[    2.639 ] [ Info     ] [ Exiting  ]     Block PointsRelaxator (41)
[    2.639 ] [ Info     ] [ Entering ] Block PointsVoronoiDelaunay (42)
[    2.639 ] [ Info     ] [ Exiting  ]     Block PointsVoronoiDelaunay (42)
[    2.639 ] [ Info     ] [ Entering ] Block MSTPointsOrderer (43)
[    2.639 ] [ Verbose  ]                  MST construction
[1]    7440 segmentation fault  ./tspart_cli 2014.jpg

```

It seams to be happing on the following line of code : 
src/Points/Savers.cc:124 
  auto start = input.pts[0]/(float)(10.f*input.scale);

Any idea on how to fix this ?

**Comment by quinor** [comment] 2021-05-21 17:20
Hi @ronansalmon, I tried reproducing the issue and it unfortunately works for me. Does it work on the sample image (`./tspart_cli res/klaudia.jpg`)? I might be able to reproduce it if you'd send me the specific file that's causing the issues. Please use my email (psorek139 ( a t ) gmail.com) for that.

As a side note, the `tspart_cli` tool is pretty basic and you may have to modify it so that it can modify the algorithm's parameters like the `tspart_gui` tool does. I can try and help you with that if you need it.

**Comment by quinor** [comment] 2021-05-25 11:16
hopefully fixed by https://github.com/quinor/tspart/commit/81a1764eababc234469421c386360a9b71ffd269

**Closed as completed** 2021-11-08 22:16 UTC
